[ORA-1465] Handle Trino connection failures in `tables` method; Bump `data_conduit` version (#386)
We've had two instances over the last couple months where either the
production or staging config is updated in some way, but not updated in
configuration. The error this created was:

```
ArgumentError: comparison of String with Hash failed
from /Users/garettarrowood/Power/nitro-web/vendor/bundle/ruby/3.3.0/gems/data_conduit-0.2.0/lib/data_conduit/adapters/trino_repository.rb:31:in `sort'
```

Instead, this patch handles the error, giving it a custom error class,
and then puts the output into the error message. Sample output:

```
{"error"=>
  {"message"=>"line 1:1: Catalog 'asdf' not found",
   "errorCode"=>44,
   "errorName"=>"CATALOG_NOT_FOUND",
   "errorType"=>"USER_ERROR",
   "errorLocation"=>{"lineNumber"=>1, "columnNumber"=>1},
   "failureInfo"=>
    {"type"=>"io.trino.spi.TrinoException",
     "message"=>"line 1:1: Catalog 'asdf' not found",
     "suppressed"=>[],
     "stack"=>
      ["io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:58)",
       "io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)",
       "io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:254)",
       "io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:222)",
  ...
```